"""
gen_cassette_bg.py — 生成磁带盒壳静态背景图 (RGB565 C array)
包含: 浅蓝紫渐变盒壳 + 花生形跑道 + 左右轮毂窗 + 中央磁带窗(线圈+磁带线)
尺寸: 296x96 (屏幕 320x240, 左右各留 12px 边距)
"""
from PIL import Image, ImageDraw
import struct, os

W, H = 296, 96
SHELL_RADIUS = 10

# 颜色 (设计稿 V8)
SHELL_LIGHT = (125, 146, 191)   # #7d92bf
SHELL_MID   = (90, 111, 149)    # #5a6f95
SHELL_DARK  = (58, 72, 104)     # #3a4868
SHELL_EDGE  = (42, 53, 82)      # #2a3552
SHELL_GLOW  = (164, 178, 208)   # #a4b2d0
TRACK_COLOR = (80, 98, 135)     # 跑道稍深
HUB_BG      = (10, 10, 10)      # #0a0a0a
TAPE_WIN_BG = (5, 8, 16)        # #050810
SCREEN_BG   = (10, 14, 23)      # #0a0e17

# 轮毂参数
HUB_R = 33           # 轮毂窗半径
HUB_LX = 45          # 左轮毂中心 x (相对图左)
HUB_RX = W - 45      # 右轮毂中心 x
HUB_CY = H // 2      # 轮毂中心 y

# 跑道参数
TRACK_R = 39         # 跑道半圆半径 (比轮毂大 6px)

# 磁带窗参数
WIN_W, WIN_H = 104, 26
WIN_X = (W - WIN_W) // 2
WIN_Y = (H - WIN_H) // 2


def make_gradient(w, h, top, mid, bot):
    """竖向三段线性渐变"""
    img = Image.new("RGB", (1, h))
    px = img.load()
    for y in range(h):
        if y < h // 2:
            t = y / (h // 2)
            r = int(top[0] + (mid[0] - top[0]) * t)
            g = int(top[1] + (mid[1] - top[1]) * t)
            b = int(top[2] + (mid[2] - top[2]) * t)
        else:
            t = (y - h // 2) / (h // 2)
            r = int(mid[0] + (bot[0] - mid[0]) * t)
            g = int(mid[1] + (bot[1] - mid[1]) * t)
            b = int(mid[2] + (bot[2] - mid[2]) * t)
        px[0, y] = (r, g, b)
    return img.resize((w, h))


def draw_peanut(draw, cx_l, cx_r, cy, r, color):
    """花生形/哑铃形: 两半圆 + 两平行线连接"""
    # 上平行线
    draw.rectangle([cx_l, cy - r, cx_r, cy - r + 1], fill=color)
    # 下平行线
    draw.rectangle([cx_l, cy + r - 1, cx_r, cy + r], fill=color)
    # 左半圆 (向左凸出)
    draw.pieslice([cx_l - r, cy - r, cx_l + r, cy + r], 90, 270, fill=color)
    # 右半圆 (向右凸出)
    draw.pieslice([cx_r - r, cy - r, cx_r + r, cy + r], 270, 90, fill=color)


def draw_coil(draw, cx, cy, side, n=7):
    """磁带窗内的磁带圈弧线 (同心半圆)
    side='left': 右半弧, 圆心在窗外左侧
    side='right': 左半弧, 圆心在窗外右侧
    """
    for i in range(1, n + 1):
        r = 40 + i * 4  # 半径 44-68
        gray = min(60, 10 + i * 7)
        color = (gray, gray, gray)
        if side == 'left':
            # 右半弧: 从 -90° 到 90° (顺时针)
            draw.arc([cx - r, cy - r, cx + r, cy + r], -90, 90, fill=color, width=1)
        else:
            # 左半弧: 从 90° 到 270°
            draw.arc([cx - r, cy - r, cx + r, cy + r], 90, 270, fill=color, width=1)


def main():
    # 1. 底色 (屏幕背景色, 圆角外区域)
    img = Image.new("RGB", (W, H), SCREEN_BG)

    # 2. 盒壳渐变 (圆角矩形 mask)
    grad = make_gradient(W, H, SHELL_LIGHT, SHELL_MID, SHELL_DARK)
    mask = Image.new("L", (W, H), 0)
    ImageDraw.Draw(mask).rounded_rectangle([0, 0, W - 1, H - 1], radius=SHELL_RADIUS, fill=255)
    img.paste(grad, (0, 0), mask)

    draw = ImageDraw.Draw(img)

    # 3. 盒壳外缘描边 (深色)
    draw.rounded_rectangle([0, 0, W - 1, H - 1], radius=SHELL_RADIUS,
                           outline=SHELL_EDGE, width=1)
    # 顶部高光
    draw.arc([1, 1, W - 2, SHELL_RADIUS * 2], 180, 360, fill=SHELL_GLOW, width=1)

    # 4. 花生形跑道 (在盒壳之上, 轮毂之下)
    draw_peanut(draw, HUB_LX, HUB_RX, HUB_CY, TRACK_R, TRACK_COLOR)
    # 跑道顶部高光
    draw.line([HUB_LX, HUB_CY - TRACK_R, HUB_RX, HUB_CY - TRACK_R],
              fill=(SHELL_LIGHT[0] // 2 + 60, SHELL_LIGHT[1] // 2 + 60, SHELL_LIGHT[2] // 2 + 60), width=1)

    # 5. 左右轮毂窗 (黑色圆 + 内阴影)
    for cx in (HUB_LX, HUB_RX):
        # 黑色内盘
        draw.ellipse([cx - HUB_R, HUB_CY - HUB_R, cx + HUB_R, HUB_CY + HUB_R], fill=HUB_BG)
        # 内圈高光 (顶部)
        draw.arc([cx - HUB_R + 2, HUB_CY - HUB_R + 2, cx + HUB_R - 2, HUB_CY + HUB_R - 2],
                 200, 340, fill=(60, 60, 70), width=1)
        # 外缘描边
        draw.ellipse([cx - HUB_R, HUB_CY - HUB_R, cx + HUB_R, HUB_CY + HUB_R],
                     outline=(30, 30, 40), width=1)

    # 6. 中央磁带窗
    draw.rounded_rectangle([WIN_X, WIN_Y, WIN_X + WIN_W, WIN_Y + WIN_H],
                           radius=3, fill=TAPE_WIN_BG, outline=(10, 13, 24), width=1)
    # 窗内阴影
    draw.rounded_rectangle([WIN_X + 1, WIN_Y + 1, WIN_X + WIN_W - 1, WIN_Y + WIN_H - 1],
                           radius=2, outline=(0, 0, 0), width=1)

    # 7. 磁带窗内线圈已移除 (P1-UI-fix: 同心圆弧太突兀), 仅保留横向磁带线

    # 8. 磁带主线 (两条横向细线, 居中)
    tape_cy = WIN_Y + WIN_H // 2
    line_y1 = tape_cy - 1
    line_y2 = tape_cy + 5
    for ly, alpha_color in [(line_y1, (70, 85, 115)), (line_y2, (55, 70, 100))]:
        draw.line([WIN_X + 8, ly, WIN_X + WIN_W - 8, ly], fill=alpha_color, width=1)

    # 9. 输出 C array (RGB565)
    out_path = os.path.join(os.path.dirname(__file__), "..", "main", "cassette_bg.h")
    out_path = os.path.normpath(out_path)
    px = img.load()
    lines = []
    lines.append("/* Auto-generated by gen_cassette_bg.py — DO NOT EDIT */")
    lines.append(f"/* Cassette shell background: {W}x{H} RGB565 */")
    lines.append("#pragma once")
    lines.append("")
    lines.append(f"#define CASSETTE_BG_W {W}")
    lines.append(f"#define CASSETTE_BG_H {H}")
    lines.append("")
    lines.append("static const uint8_t cassette_bg_data[] = {")
    row_bytes = []
    for y in range(H):
        row = []
        for x in range(W):
            r, g, b = px[x, y]
            rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            # 低字节在前 (小端), 与 reel_img.h 一致
            row.append(f"0x{rgb565 & 0xFF:02X},0x{rgb565 >> 8:02X}")
        row_bytes.append("    " + ",".join(row) + ",")
    lines.extend(row_bytes)
    lines.append("};")
    lines.append("")
    lines.append("static const lv_img_dsc_t cassette_bg_dsc = {")
    lines.append("    .header = {.magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_RGB565,")
    lines.append(f"               .w = {W}, .h = {H}, .stride = {W * 2}}},")
    lines.append("    .data_size = sizeof(cassette_bg_data),")
    lines.append("    .data = cassette_bg_data,")
    lines.append("};")

    with open(out_path, "w", encoding="utf-8", newline="") as f:
        f.write("\n".join(lines) + "\n")

    # 同时保存 PNG 供预览
    png_path = os.path.join(os.path.dirname(__file__), "cassette_bg_preview.png")
    img.save(png_path)
    print(f"OK: {out_path} ({W}x{H}, {W*H*2} bytes)")
    print(f"OK: {png_path}")


if __name__ == "__main__":
    main()
